apiVersion: v2
name: unikorn-core
description: A Helm chart for deploying Unikorn Core

type: application

version: v0.1.94-rc3
appVersion: v0.1.94-rc3

icon: https://assets.unikorn-cloud.org/images/logos/dark-on-light/icon.svg

dependencies:
- name: unikorn-common
  version: v0.1.12
  repository: https://unikorn-cloud.github.io/helm-common
