apiVersion: v2
name: core
description: A Helm chart for deploying Unikorn Core

type: application

version: v0.1.47
appVersion: v0.1.47

icon: https://assets.unikorn-cloud.org/images/logos/dark-on-light/icon.svg
