apiVersion: v2
name: unikorn
description: A Helm chart for deploying Unikorn Core

type: application

version: 0.1.1
appVersion: 0.1.1

icon: https://raw.githubusercontent.com/eschercloudai/unikorn/main/icons/default.png
